version: '3.7'
services:
  daietto-website-db:
    platform: linux/x86_64
    container_name: daietto-website-db
    image: mysql:5.7
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./_db:/docker-entrypoint-initdb.d
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: daietto
    networks:
      - daietto-website-wp
  daietto-website-phpmyadmin:
    container_name: daietto-website-phpmyadmin
    depends_on:
      - daietto-website-db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8085:80'
    environment:
      PMA_HOST: daietto-website-db
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - daietto-website-wp
  daietto-website-wordpress:
    container_name: daietto-website-wordpress
    depends_on:
      - daietto-website-db
    build:
      context: ./
    ports:
      - '80:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: daietto-website-db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      DOMAIN: daietto.test
    networks:
      daietto-website-wp:
        aliases:
          - daietto.test
networks:
  daietto-website-wp:
volumes:
  db_data: